### ISSUE TITLE
Update ocp client

### ISSUE THREAD

**Issue by kaovilai** [openshift-labs/workshop-terminal#19]
There are newer versions on
https://mirror.openshift.com/pub/openshift-v4/clients/ocp/

I have been pinged about oc being out of date. Probably nothing major.

**Comment by kaovilai** [comment]
Specifically, the RHPDS catalog is right now at version 4.1.3 serverside and they want the oc client inside homeroom to match that version.

I see there's already 4.1.7 out.

[This file](https://github.com/openshift-labs/workshop-terminal/blob/develop/terminal/bin/oc) and the [Dockerfile](https://github.com/openshift-labs/workshop-terminal/blob/develop/terminal/Dockerfile) probably needs updating to include other client versions

**Comment by GrahamDumpleton** [comment]
Updated to 4.1.7 in 2.11.2. Updated derived dashboard image still to come.
